input_data: '/workspaces/VoxG/data/raw'
normalization_data: '/workspaces/VoxG/data/normalization'
processed_data: '/workspaces/VoxG/data/processed' 
gt_data: '/workspaces/VoxG/data/ground_truth'
generated_data: '/worskapces/VoxG/data/generated'

sampling:
  sampling_rate: 44100.0
  frame_len: 1024
  hop_len: 256