input_data: ${{ VOXG_INPUT_DATA }}
normalization_data: ${{ VOXG_NORMALIZATION_DATA }}
processed_data: ${{ VOXG_PROCESSED_DATA }}
gt_data: ${{ VOXG_GT_DATA }}
generated_data: ${{ VOXG_GENERATED_DATA }}
splits: ${{ VOXG_SPLITS_DATA }}

data:
  split_id: 0

sampling:
  sampling_rate: 44100.0
  frame_len: 1024
  hop_len: 256

training:
  batch_size: 30
  per_epoch: 600
  per_epoch_valid: 10
  epochs: 950
  critic_inloops: 5
  blocks_per_file: 6
  block_len: 128

  filter_length: 5
  num_features: 64

  activation_generator: 'relu'
  activation_critic: 'leaky_relu'
  optimizer: 'rmsprop'

  reconstruction_loss_lambda: 0.001
  learning_rate: 0.00005
  dropout: 0.0